service: serverless-golang-todoapp

package:
  artifact: package.zip

provider:
  name: aws
  runtime: python2.7
  stage: ${env:STAGE}
  region: ${env:AWS_DEFAULT_REGION}

functions:
  ping:
    handler: handler.Ping
    events:
      - http:
          path: ping
          method: get
