service: serverless-golang-todoapp

package:
  artifact: package.zip

custom:
  currentStage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  runtime: python2.7
  stage: ${env:STAGE}
  region: ${env:AWS_DEFAULT_REGION}
  iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:DescribeTable
      - dynamodb:Query
      - dynamodb:Scan
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:UpdateItem
      - dynamodb:DeleteItem
    Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.currentStage}-*

resources: ${file(resources.yml)}

functions:
  ping:
    handler: handler.Ping
    events:
      - http:
          path: ping
          method: get
  createTodos:
    handler: handler.CreateTodo
    events:
      - http:
          path: todos
          method: post
    environment:
      STAGE: ${self:custom.currentStage}
  fetchAllTodo:
    handler: handler.FetchAllTodo
    events:
      - http:
          path: todos
          method: get
    environment:
      STAGE: ${self:custom.currentStage}
